behaviors:
  Feedback Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      shared_critic: False
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
      entropy_coefficient: 0.02
    network_settings:
      normalize: False
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: False
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: False
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: False
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 100000
    time_horizon: 64
    summary_freq: 1000
    threaded: False
    self_play: null
    behavioral_cloning: null