behaviors:
  Feedback Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 3200
      learning_rate: 0.0005
      beta: 0.02
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 5
      shared_critic: False
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: True
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: False
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.2
      curiosity:
        gamma: 0.99
        strength: 0.1
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 5000
    max_steps: 500000
    time_horizon: 128
    summary_freq: 1000
    threaded: False
    self_play: null
    behavioral_cloning: null
